language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      sudo: false
    - os: linux
      compiler: clang
      sudo: false

    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env: DIST=trusty
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      env: DIST=trusty

    - os: osx
      compiler: gcc
    - os: osx
      compiler: clang


addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - lcov

before_install:
  - pip install --user codecov
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update --quiet ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install lcov; fi
  - if [[ "$DIST" == "trusty" -a "$CC" == "clang" ]]; then sudo apt-get install gcc-4.6; fi


script:
  - mkdir build && cd build
  - cmake .. -DENABLE_COVERAGE=On && make && make test
  - make gcov
  - make lcov

after_success:
  - codecov
