language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      sudo: false
    - os: linux
      compiler: clang
      sudo: false

    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang

    - os: osx
      compiler: gcc
      before_install:
        - brew update --quiet >& /dev/null
        - brew upgrade gcc
        - brew install lcov
    - os: osx
      compiler: clang
      before_install:
        - brew update --quiet >& /dev/null
        - brew upgrade gcc
        - brew install lcov


addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - lcov
      - gfortran


script:
  - mkdir build && cd build
  - cmake .. -DENABLE_COVERAGE=On && make && make test
  - make gcov
  - make lcov

after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov
